version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: css-loader
    versions:
    - 5.0.1
    - 5.0.2
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.1.4
    - 5.2.0
    - 5.2.1
    - 5.2.2
    - 5.2.3
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.5
    - 1.3.6
    - 1.3.7
    - 1.3.8
    - 1.3.9
    - 1.4.0
    - 1.4.1
    - 1.5.0
  - dependency-name: autoprefixer
    versions:
    - 10.2.4
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
